### ISSUE TITLE
Spade Installation Error

### ISSUE THREAD

**Issue by aagamboa** [nolanlab/spade#146]
Hi, 
I was able to install devtools and Rclusterpp no problem, but keep getting an error 'ERROR: compilation failed for package 'spade'' when trying to install spade. I have tried installing with install_github and also through Rstudio and the terminal using the *tar.gz file. I am working on macOS Catalina Version 10.15.7 and R version 4.1.1. 

Let me know if I should provide any other information, I appreciate your help.
Thank you,
Alicia

Below is the console output: 
 
```
> devtools::install_github("nolanlab/spade")
Downloading GitHub repo nolanlab/spade@HEAD
✓  checking for file ‘/private/var/folders/6r/_jxvdf_j3rqg6r1j2zqb2ll40000gn/T/RtmptsBybz/remotes2f8154003e0f/nolanlab-spade-356955f/DESCRIPTION’ ...
─  preparing ‘spade’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘spade_1.10.4.tar.gz’
   
* installing *source* package ‘spade’ ...
** using staged installation
checking for gcc... /usr/local/opt/llvm/bin/clang
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/local/opt/llvm/bin/clang accepts -g... yes
checking for /usr/local/opt/llvm/bin/clang option to accept ISO C89... none needed
checking how to run the C preprocessor... /usr/local/opt/llvm/bin/clang -E
checking whether we are using the GNU C++ compiler... yes
checking whether /usr/local/opt/llvm/bin/clang++ accepts -g... yes
checking how to run the C++ preprocessor... /usr/local/opt/llvm/bin/clang++ -E
checking for /usr/local/opt/llvm/bin/clang option to support OpenMP... unsupported
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking parallel/algorithm usability... no
checking parallel/algorithm presence... no
checking for parallel/algorithm... no
"Parallel STL not found using default"
configure: creating ./config.status
config.status: creating src/Makevars
** libs
/usr/local/opt/llvm/bin/clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I"/usr/local/opt/gettext/include" -I"/usr/local/opt/llvm/include" -I"/usr/local/opt/libomp/include" -isysroot "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk" -Xclang -fopenmp  -DPACKAGE_NAME=\"spade\" -DPACKAGE_TARNAME=\"spade\" -DPACKAGE_VERSION=\"0.20\" -DPACKAGE_STRING=\"spade\ 0.20\" -DPACKAGE_BUGREPORT=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -fPIC  -g -O2 -Wall -pedantic -std=c++11 -mtune=native -pipe -c cluster.cc -o cluster.o
In file included from cluster.cc:16:
/usr/local/Cellar/llvm/13.0.0/lib/clang/13.0.0/include/omp.h:483:39: error: expected 'match' clause on 'omp declare variant' directive
    #pragma omp begin declare variant match(device={kind(host)})
                                      ^
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:1640:17: note: expanded from macro 'match'
#define match                   Rf_match
                                ^
In file included from cluster.cc:16:
/usr/local/Cellar/llvm/13.0.0/lib/clang/13.0.0/include/omp.h:486:39: error: expected 'match' clause on 'omp declare variant' directive
    #pragma omp begin declare variant match(device={kind(nohost)})
                                      ^
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:1640:17: note: expanded from macro 'match'
#define match                   Rf_match
                                ^
cluster.cc:214:46: warning: 'mem_fun_ref<bool, (anonymous namespace)::ACluster>' is deprecated [-Wdeprecated-declarations]
                        c_end = std::partition(c_beg, c_end, std::mem_fun_ref(&ACluster::get_valid));
                                                                  ^
/usr/local/opt/llvm/bin/../include/c++/v1/__functional/mem_fun_ref.h:158:1: note: 'mem_fun_ref<bool, (anonymous namespace)::ACluster>' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX11 inline _LIBCPP_INLINE_VISIBILITY
^
/usr/local/opt/llvm/bin/../include/c++/v1/__config:1004:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/usr/local/opt/llvm/bin/../include/c++/v1/__config:993:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
cluster.cc:221:47: warning: 'mem_fun_ref<bool, (anonymous namespace)::ACluster>' is deprecated [-Wdeprecated-declarations]
                                c_end = std::partition(c_beg, c_end, std::mem_fun_ref(&ACluster::get_valid));
                                                                          ^
/usr/local/opt/llvm/bin/../include/c++/v1/__functional/mem_fun_ref.h:158:1: note: 'mem_fun_ref<bool, (anonymous namespace)::ACluster>' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX11 inline _LIBCPP_INLINE_VISIBILITY
^
/usr/local/opt/llvm/bin/../include/c++/v1/__config:1004:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/usr/local/opt/llvm/bin/../include/c++/v1/__config:993:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
cluster.cc:274:45: warning: 'mem_fun_ref<bool, (anonymous namespace)::ACluster>' is deprecated [-Wdeprecated-declarations]
                c_end = std::partition(c_beg, c_end, std::mem_fun_ref(&ACluster::get_valid));
                                                          ^
/usr/local/opt/llvm/bin/../include/c++/v1/__functional/mem_fun_ref.h:158:1: note: 'mem_fun_ref<bool, (anonymous namespace)::ACluster>' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX11 inline _LIBCPP_INLINE_VISIBILITY
^
/usr/local/opt/llvm/bin/../include/c++/v1/__config:1004:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/usr/local/opt/llvm/bin/../include/c++/v1/__config:993:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
3 warnings and 2 errors generated.
make: *** [cluster.o] Error 1
ERROR: compilation failed for package ‘spade’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/spade’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/6r/_jxvdf_j3rqg6r1j2zqb2ll40000gn/T//RtmptsBybz/file2f815bea75de/spade_1.10.4.tar.gz’ had non-zero exit status

```
